name: ci-golang-workflow

on: 
  pull_request:
    branchs:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup Golang
        uses: actions/setup-go@v2
        with: 
          go-version: 1.21
      - 
        name: Test
        run: go test
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: carlosallexandre/fc-devops-ci-math:latest